-- 公司列表
CREATE TABLE COMPANY
(
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT '流水號',
    code VARCHAR(100) NOT NULL COMMENT '公司代號'  ,
    name VARCHAR(255) NOT NULL COMMENT '公司名稱',
    is_active TINYINT DEFAULT 1 NOT NULL COMMENT '是否營業',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '創建時間',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '更新時間'
);

ALTER TABLE COMPANY ADD CONSTRAINT UK_ID UNIQUE (CODE);


